//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string NomeLivro { get; set; }
        public string NomeAutor { get; set; }
        public string Descricao { get; set; }
        public string Categoria { get; set; }
        public string URL_CAPA { get; set; }
        public string URL_BOOK { get; set; }
        public string Matrix { get; set; }
    }
}
