CREATE DATABASE LIVRO
GO

USE LIVRO
GO

CREATE TABLE BOOK(
ID INT NOT NULL,
NOMELIVRO VARCHAR(500) NOT NULL,
NOMEAUTOR VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(MAX) NOT NULL,
CATEGORIA VARCHAR(30) NULL,
URL_CAPA VARCHAR(500) NOT NULL,
URL_BOOK VARCHAR(500) UNIQUE NOT NULL,
MATRIX VARCHAR(MAX) NULL
);
